### PR TITLE
Fixed crash when rasining exception in get_p2fcdata + FORS2 crash fix

### PR DESCRIPTION
**Pull request by HeloiseS**
Hi, 

I've been testing fcmaker on my system with the --demo . When using a SOFI OB I found the code crashed instead of raising the inbuilt exception. 

It looks to me like the variable name `inst` does not exist and should be fc_parrams['inst].

This fixed my issue locally so I thought I'd do a pull request (this is my first pull request so I'm sorry if this should have been done another way ^^)

Cheers

### CODE REVIEW

**Comment by fpavogt** [comment]
Thanks for this. The fix is correct. I'll incorporate it in the coming days.

**Comment by HeloiseS** [comment]
Hi!

I just moved the instrument check in the get_p2fcdata function to the top so that if an exception must be raised it is done before checking for the presence of an ephemeris which is why it crashed before raising the correct exception when calling FORS2 OBs.

You should be able to merge this directly to your branch since all I did was move a block of code up :)

Cheers,
Heloise

**Comment by HeloiseS** [comment]
> Thanks for this. The fix is correct. I'll incorporate it in the coming days.

Just saw this pull request is still open. :)

**Comment by fpavogt** [comment]
Thanks for the reminder, and sorry about the delay dealing with this. Job and continent change got me distracted over the past few months. I just pushed [v105,](https://github.com/fpavogt/fcmaker/tree/v105.0.0) that deals with the problem. In the end, I went for a different fix, because the error you encountered was (strictly speaking) related to a faulty ephemeris file (which could also happen for a supported instrument). So I added some additional checks to make sure problematic ephemeris files raise a cleaner `Exception`. 

So now, the code will fail either because the ephemeris file is faulty, or because FORS support is not implemented.

Thanks again for spotting and reporting this !

**Pull request closed without merging**
